Project Library: lbk_library.element_set.ElementSet Class Reference
lbk_library.element_set.ElementSet Class Reference
Public Member Functions
None __init__ (self, Dbal dbref, str table_name, type element_type, str where_column=None, Any where_value=None, str order_by_column=None, int limit=None, int offset=None)
None append (self, Element element)
None insert (self, int index, Element element)
Element get (self, int location)
None delete (self, int location)
Dbal get_dbref (self)
str get_table (self)
None set_table (self, str table)
list[Element] get_property_set (self)
None set_property_set (self, list[Element] property_set)
int get_number_elements (self)
list[str] build_option_list (self, str key)
Iterator __iter__ (self)
Element __next__ (self)
None __reset__ (self)
Private Attributes
__property_set
__table
__position
Detailed Description
The base class for a set of Elements in the database.
The set of Element types must be all the same type. The class
implements the "Iterator" interface.
Constructor & Destructor Documentation
__init__()
None lbk_library.element_set.ElementSet.__init__ (self, Dbal dbref, str table_name, type element_type, str where_column = None, Any where_value = None, str order_by_column = None, int limit = None, int offset = None)
Get a list of elements from the database table.
This will return a list of rows from the database table where
the 'where_column' contains the 'where_value'. The list can
optionally be sorted ascending by the values in the
'order_by_column'.
The number of rows can be optionally limited to the number of
rows in 'limit and the search will start at the row number
(zero based) given in 'offset'.
Parameters:
    dbref (Dbal): reference to the database holding the element.
    table_name (str): database table to search for the element
        values.
    element_type (type): the type of element in the set,
    where_column (str): The key column of the table containing
        the key value to determine the elements being retrieved.
        If null, all rows are retrieved.
    where_value (Any): The key value to retrieve. Required if
        where_column is set.
    order_by_column (str): one or more column names separated
        by commas to order the resulting set of elements.
    limit (int): number of rows to retrieve, defaults to all.
    offset (int): row number to start retrieval, 0 based,
        defaults to row 0.
References lbk_library.gui.dialog.Dialog.__dbref, lbk_library.element_set.ElementSet.__position, lbk_library.element_set.ElementSet.__property_set, lbk_library.element_set.ElementSet.__table, and lbk_library.element_set.ElementSet.append().
Member Function Documentation
__iter__()
Iterator lbk_library.element_set.ElementSet.__iter__ (self)
Generate an Iterator object for this element.
Returns:
    (Iterator) This ElementSet reference as the Iterator Object.
__next__()
Element lbk_library.element_set.ElementSet.__next__ (self)
Return the next Element in the set.
Returns:
    (Element) next element in the set
Raises:
    StopIteration When the last element of the set has been
    returned.
References lbk_library.element_set.ElementSet.__position, lbk_library.element_set.ElementSet.__reset__(), and lbk_library.element_set.ElementSet.get_property_set().
__reset__()
None lbk_library.element_set.ElementSet.__reset__ (self)
Reset the iterator position to the beginning.
append()
None lbk_library.element_set.ElementSet.append (self, Element element)
Append an element to the end of the property set.
Parameters:
    element (Element): the element to append to the property set
References lbk_library.element_set.ElementSet.get_property_set(), and lbk_library.element_set.ElementSet.insert().
build_option_list()
list[str] lbk_library.element_set.ElementSet.build_option_list (self, str key)
Build a list from an element property set.
This will be for properties such as entry_indices or names for
use primarily in setting ComboBox selection lists.
Parameters:
    key (str): the element property to display in the
        option list
Return:
    (list) List of element properties as strings
References lbk_library.element_set.ElementSet.get_property_set().
delete()
None lbk_library.element_set.ElementSet.delete (self, int location)
Delete an element from the property set at the given index.
Parameters:
    location (int): index of the element to be deleted
        (zero based)
References lbk_library.element_set.ElementSet.get_property_set().
get()
Element lbk_library.element_set.ElementSet.get (self, int location)
Get an element from the property set at the given index.
Parameters:
    location (int): index of the element to be retrieved
        (zero based)
References lbk_library.element_set.ElementSet.get_property_set().
get_dbref()
Dbal lbk_library.element_set.ElementSet.get_dbref (self)
Get the database reference.
Returns:
    (Dbal) The database reference for this element set.
References lbk_library.gui.dialog.Dialog.__dbref.
get_number_elements()
int lbk_library.element_set.ElementSet.get_number_elements (self)
Get the number of elements in the element set.
Returns:
    (int) Number of elements in the element set.
References lbk_library.element_set.ElementSet.get_property_set().
get_property_set()
list[Element] lbk_library.element_set.ElementSet.get_property_set (self)
Get the property set for this element set.
Returns:
    (list) The property set for this element set.
References lbk_library.element_set.ElementSet.__property_set.
get_table()
str lbk_library.element_set.ElementSet.get_table (self)
Get the database table name.
Returns:
    (str) The table name for this element set.
References lbk_library.element_set.ElementSet.__table.
insert()
None lbk_library.element_set.ElementSet.insert (self, int index, Element element)
Insert an element into the property set at a specific index.
Parameters:
    index (int): location to insert the element (zero based)
    element (Element): the element to insert into the
        property set
References lbk_library.element_set.ElementSet.get_property_set(), and lbk_library.element_set.ElementSet.insert().
set_property_set()
None lbk_library.element_set.ElementSet.set_property_set (self, list[Element] property_set)
Set the property set array for this element set.
Parameters:
    property_set (list): property set for this element set. The
    list may be empty
References lbk_library.element_set.ElementSet.__property_set.
set_table()
None lbk_library.element_set.ElementSet.set_table (self, str table)
Set the database table name.
Parameters:
    table (str): The table name for this element set.
Member Data Documentation
__position
lbk_library.element_set.ElementSet.__position private
__property_set
lbk_library.element_set.ElementSet.__property_set private
__table
lbk_library.element_set.ElementSet.__table private
The documentation for this class was generated from the following file:
src/lbk_library/element_set.py