Project Library: lbk_library.element.Element Class Reference
lbk_library.element.Element Class Reference
Public Member Functions
None __init__ (self, DataFile datafile, str table_name, dict[str, Any] default_values=None)
dict[str, Any] get_properties_from_datafile (self, str column_name, Any column_value)
int add (self)
bool delete (self)
bool update (self)
dict[str, Any] get_properties (self)
dict[str, list[str, bool, str]] set_properties (self, dict[str, Any] properties)
None set_validated_property (self, str property_name, bool is_valid, Any validated_value, Any default_value)
int get_record_id (self)
dict[str, Any] set_record_id (self, int record_id)
str get_remarks (self)
dict[str, Any] set_remarks (self, str remarks)
DataFile get_datafile (self)
str get_table (self)
dict[str, Any] get_initial_values (self)
None set_initial_values (self, dict[str, Any] initial_value_set)
None update_property_flags (self, str name, Any value, bool valid)
bool get_value_changed_flag (self, str entry_name)
bool set_value_changed_flag (self, str entry_name, Any entry_value)
bool have_values_changed (self)
None clear_value_changed_flags (self)
bool get_value_valid_flag (self, str entry_name)
bool set_value_valid_flag (self, str entry_name, bool entry_valid)
bool is_element_valid (self)
None clear_value_valid_flags (self)
Public Attributes
Validate validate = Validate()
Protected Member Functions
Any _get_property (self, str name)
None _set_property (self, str name, Any value)
Protected Attributes
dict _defaults = {"record_id": 0, "remarks": ""}
Private Attributes
DataFile __datafile = datafile
str __table = table_name
dict __properties = {}
dict __initial_values = {}
dict __changed_properties = {}
dict __properties_valid = {}
Detailed Description
This is the base class for types of information in the data file.
Element contains methods to get, add, delete and update information
in the data file. The set_properties() method must be overridden by
the child classes for the specific type of element being implemented.
Constructor & Destructor Documentation
__init__()
None lbk_library.element.Element.__init__ (self, DataFile datafile, str table_name, dict[str, Any] default_values = None)
Initialize a new Element object.
Parameters:
    datafile (DataFile): reference to the data file holding the element
    table_name (str): data file table to search for the element
        values.
    default_values (dict[str, Any]): the set of default values for this
        element, default is None. If not given, built-in defaults of
        {'record_id': 0, 'remarks': ''} will be used.
Member Function Documentation
_get_property()
Any lbk_library.element.Element._get_property (self, str name) protected
Get an individual property value by Name.
Parameters:
    name (str): name of property to retrieve.
Returns:
    (Any) value of property if property is defined.
Raises:
    KeyError: if name is not a valid property name.
References __properties.
Referenced by test_setup.Fish.get_name(), get_record_id(), get_remarks(), test_setup.Fish.get_species(), and test_setup.Fish.get_tank_number().
_set_property()
None lbk_library.element.Element._set_property (self, str name, Any value) protected
Set an individual property.
This is a low level function with no error checking.
Parameters:
    name (str): property name
    value (Any): value of this property
References __properties.
Referenced by test_setup.Fish.set_name(), test_setup.Fish.set_species(), test_setup.Fish.set_tank_number(), and set_validated_property().
add()
int lbk_library.element.Element.add (self)
Add an element to the data file.
Returns:
    (int) unique id of the newly added element or False if
        add failed.
References __datafile, get_datafile(), get_properties(), and get_table().
clear_value_changed_flags()
None lbk_library.element.Element.clear_value_changed_flags (self)
Clear the set of 'value changed' flags.
References __changed_properties.
Referenced by test_setup.Fish.__init__().
clear_value_valid_flags()
None lbk_library.element.Element.clear_value_valid_flags (self)
Clear the set of 'valid' flags.
References __properties_valid.
delete()
bool lbk_library.element.Element.delete (self)
Delete an element from the data file.
This always uses the record_id column and value to identify
the record to delete.
Returns:
    (bool) True if the deletion was successful, False if not.
References __datafile, get_datafile(), get_record_id(), and get_table().
get_datafile()
DataFile lbk_library.element.Element.get_datafile (self)
Get the data file reference for this element.
Returns:
    (DataFile) A reference to the current data file.
References __datafile.
Referenced by add(), delete(), and update().
get_initial_values()
dict[str, Any] lbk_library.element.Element.get_initial_values (self)
Get the intial values for the element.
Returns:
    (dict) the initial values assigned to the element's
        properties.
References __initial_values.
get_properties()
dict[str, Any] lbk_library.element.Element.get_properties (self)
Get the element properties as a dict() of property_names->values.
Returns:
    (dict) The element properties.
References __properties.
Referenced by test_setup.Fish.__init__(), add(), is_element_valid(), and update().
get_properties_from_datafile()
dict[str, Any] lbk_library.element.Element.get_properties_from_datafile (self, str column_name, Any column_value)
Retrieve the properties of a single element from the data file.
The requested element is selected by the table column name and
the key column value designated.
Parameters:
    column_name (str): within the table containing the key
        values
    column_value (Any): Key value requested
Returns:
    (dict) Row containing requested element if successful or an
        empty dict object if not.
References __datafile, __properties, and __table.
Referenced by test_setup.Fish.__init__().
get_record_id()
int lbk_library.element.Element.get_record_id (self)
Get the Elements's record_id.
Returns:
    (int) The Elements's record_id or 0 if no record_id is
        assigned
References _defaults, and _get_property().
Referenced by delete().
get_remarks()
str lbk_library.element.Element.get_remarks (self)
Get the remarks for this Element.
Returns:
    (str) The remarks for this Element, the default value if no
        remarks are assigned.
References _defaults, and _get_property().
get_table()
str lbk_library.element.Element.get_table (self)
Get the name of the data file table for the child.
Returns:
    (str) The table name for this element.
References __table.
Referenced by add(), delete(), and update().
get_value_changed_flag()
bool lbk_library.element.Element.get_value_changed_flag (self, str entry_name)
Get an value changed flag for the given property.
The flag will be True if the property has changed from the
initial value, False if not.
Parameters:
    entry_name (str): name of entry to check.
Returns:
    (bool) The state of the entry changed flag
Raises:
    KeyError if entry_name is not a valid name
References __changed_properties.
get_value_valid_flag()
bool lbk_library.element.Element.get_value_valid_flag (self, str entry_name)
Get a value valid flag.
Parameters:
    entry_name (str): entry to get validation flag.
Returns:
    (bool) the resulting flag value.
Raises:
    KeyError if entry_name is not in the value valid flag set
References __properties_valid.
Referenced by is_element_valid().
have_values_changed()
bool lbk_library.element.Element.have_values_changed (self)
Check the entry changed flags.
The result is True if any value changed flag is set, False
otherwise.
Returns:
    (bool) True if any entry has changed, False if no entry
        has changed.
References __changed_properties.
is_element_valid()
bool lbk_library.element.Element.is_element_valid (self)
Check the Element validity.
Implicit here is that all properties have been checked for
validity. This should be done as part of the element
construction and modification.
Returns:
    (bool) True if all element values are valid,
        False otherwise.
Raises:
    KeyError if entry_name is not a valid name.
References get_properties(), and get_value_valid_flag().
set_initial_values()
None lbk_library.element.Element.set_initial_values (self, dict[str, Any] initial_value_set)
Set the initial settings for the element entries.
The initial values are set. The changed flags are initialized
to false. If the record_id is an integer greater than 0, the
valid flags are initialized to True, otherwise, False.
Parameters:
    initial_value_set (dict): holds the intial values assigned to
        the element's properties.
Raises:
    TypeError if 'initial_value_set' is not a dict
References __initial_values.
Referenced by test_setup.Fish.__init__().
set_properties()
dict[str, list[str, bool, str]] lbk_library.element.Element.set_properties (self, dict[str, Any] properties)
Set the values of the Element properties array.
This must be overridden and called by the child class to handle
the full set of properties. This method sets the common
properties 'record_id' (contained in all Elements) and
'remarks' (contained in many Elements).
Each property is validated for type and value within an
acceptable range, with unacceptable values set to the
respective default values. Properties not part of the element
are discarded.
Parameters:
    properties (dict): object holding the element values. Keys
        must match the required keys of the element being
        modified, properties may be sparse.
Returns:
    (dict[str, list[str, bool, str]]) the results of setting the
        values as key:validation_results pairs. May be empty or
        sparse.
Reimplemented in test_setup.Fish.
References set_record_id(), and set_remarks().
Referenced by test_setup.Fish.__init__().
set_record_id()
dict[str, Any] lbk_library.element.Element.set_record_id (self, int record_id)
Set the Element's entry index.
Parameters:
    record_id (int):  the new record_id for the Element. Must be
        an integer greater than 0 and must be unique when
        Element is stored to the data file (not checked). If the
        supplied record_id is not valid, the record_id is set
        to __defaults['record_id'].
Returns:
    (dict) {
        ['entry'] - (int) the updated record_id.
        ['valid'] - (bool) True if the operation suceeded, False
            otherwise.
        ['msg'] - (str) Error message if not valid.
    }
References _defaults, set_validated_property(), update_property_flags(), and validate.
Referenced by set_properties().
set_remarks()
dict[str, Any] lbk_library.element.Element.set_remarks (self, str remarks)
Set the remarks for this Item.
The remarks are optional and may be empty.
Parameters:
    remarks: (str) For this Element, may be empty.
Returns:
    (dict) {
        ['entry'] - (int) the updated remarks for this Element.
        ['valid'] - (bool) True if the operation suceeded, False
            otherwise.
        ['msg'] - (str) Error message if not valid.
    }
References _defaults, set_validated_property(), update_property_flags(), and validate.
Referenced by set_properties().
set_validated_property()
None lbk_library.element.Element.set_validated_property (self, str property_name, bool is_valid, Any validated_value, Any default_value)
Store a validated value in the property set.
If the value is valid, store the provided value, otherwise store
the given default value.
Parameters:
    property_name (str): the name of the property to store.
    is_valid (bool): is the validated value acceptable.
    validated_value (Any): the value to store if the validated
        value is valid.
    default_value (Any): the value to store if the validated
        value is not valid.
References _set_property().
Referenced by set_record_id(), and set_remarks().
set_value_changed_flag()
bool lbk_library.element.Element.set_value_changed_flag (self, str entry_name, Any entry_value)
Set an value changed flag.
The given value changed flag is set True if the entry value has
changed from the initial value, False if not.
Parameters:
    entry_name (str): name of entry that changed.
    entry_value: (Any): value of the entry that changed.
Returns:
    (bool) The updated state of the entry changed flag.
References __changed_properties, and __initial_values.
Referenced by update_property_flags().
set_value_valid_flag()
bool lbk_library.element.Element.set_value_valid_flag (self, str entry_name, bool entry_valid)
Set a entry valid flag.
Parameters:
    entry_name (str): entry to set validation flag.
    entry_valid (bool): True if entry is valid, False if not.
Returns:
    (bool) the resulting flag value.
References __properties_valid.
Referenced by update_property_flags().
update()
bool lbk_library.element.Element.update (self)
Update an element in the data file.
This always uses the record_id column and value to identify
the record to update.
Returns:
    (bool) True if the update was successful, False if not.
References get_datafile(), get_properties(), and get_table().
update_property_flags()
None lbk_library.element.Element.update_property_flags (self, str name, Any value, bool valid)
Update the flags for a property member.
This updates the change flag and the valid flag for the named
property member.
Parameters:
    name (str): the name of the specific property member.
    value (Any): the new property value.
    valid (bool): True if new value is valid, false if not.
References set_value_changed_flag(), and set_value_valid_flag().
Referenced by set_record_id(), and set_remarks().
Member Data Documentation
__changed_properties
dict lbk_library.element.Element.__changed_properties = {} private
Referenced by clear_value_changed_flags(), get_value_changed_flag(), have_values_changed(), and set_value_changed_flag().
__datafile
DataFile lbk_library.element.Element.__datafile = datafile private
Referenced by add(), delete(), get_datafile(), lbk_library.element_set.ElementSet.get_datafile(), lbk_library.gui.dialog.Dialog.get_datafile(), and get_properties_from_datafile().
__initial_values
dict lbk_library.element.Element.__initial_values = {} private
Referenced by get_initial_values(), set_initial_values(), and set_value_changed_flag().
__properties
dict lbk_library.element.Element.__properties = {} private
Referenced by _get_property(), _set_property(), get_properties(), and get_properties_from_datafile().
__properties_valid
dict lbk_library.element.Element.__properties_valid = {} private
Referenced by clear_value_valid_flags(), get_value_valid_flag(), and set_value_valid_flag().
__table
str lbk_library.element.Element.__table = table_name private
Referenced by get_properties_from_datafile(), get_table(), lbk_library.element_set.ElementSet.get_table(), and lbk_library.element_set.ElementSet.set_table().
_defaults
lbk_library.element.Element._defaults = {"record_id": 0, "remarks": ""} protected
Referenced by get_record_id(), get_remarks(), set_record_id(), and set_remarks().
validate
Validate lbk_library.element.Element.validate = Validate()
Referenced by test_setup.Fish.set_name(), set_record_id(), set_remarks(), test_setup.Fish.set_species(), and test_setup.Fish.set_tank_number().
The documentation for this class was generated from the following file:
src/lbk_library/element.py