Project Library: lbk_library.datafile.DataFile Class Reference
lbk_library.datafile.DataFile Class Reference
Public Member Functions
None new_file (cls, str filename, list[str] sql_statements)
None __init__ (self)
bool sql_connect (self, str datafile)
sqlite3.Cursor sql_query (self, str query, dict values={})
None sql_close (self)
bool sql_is_connected (self)
Any sql_validate_value (self, Any var)
int sql_nextid (self, sqlite3.Cursor query_result)
dict sql_fetchrow (self, sqlite3.Cursor query_result)
list sql_fetchrowset (self, sqlite3.Cursor query_result)
str sql_query_from_array (self, dict query, dict value_set={})
Public Attributes
datafile_name = datafile
Protected Member Functions
None _sql_error (self, str sql_text="")
Private Member Functions
str __sql_delete_statement (self, dict query)
str __sql_insert_statement (self, dict query, dict[str, Any] value_set)
str __sql_select_statement (self, dict query)
str __sql_update_statement (self, dict query, dict value_set)
dict __dict_factory (self, sqlite3.Cursor cursor, list[Any] row)
Private Attributes
str __datafile_name = ""
sqlite3.Connection __connection = None
Detailed Description
Implement a DataFile for permanent storage of information.
This supplies the required minimum functionality to use the Sqlite3
datafile.
This is inspired by and modeled on the DataFile of PHPBB3, much
simplified and implemented in python.
Constructor & Destructor Documentation
__init__()
None lbk_library.datafile.DataFile.__init__ (self)
Create a new DataFile object.
Member Function Documentation
__dict_factory()
dict lbk_library.datafile.DataFile.__dict_factory (self, sqlite3.Cursor cursor, list[Any] row) private
Set the return from a fetchrow function to be a dict object.
__sql_delete_statement()
str lbk_library.datafile.DataFile.__sql_delete_statement (self, dict query) private
Build the sql DELETE statement.
Statement Form:  DELETE FROM table WHERE x = y
Parameter:
    query (dict): {
        ['type'] -> (str) 'DELETE',
        ['table'] -> (str) name of table to access
        ['where'] -> (str) the sql where_clause contents
            (without the 'WHERE').
Returns:
    (str) the fully formed DELETE statement.
Referenced by sql_query_from_array().
__sql_insert_statement()
str lbk_library.datafile.DataFile.__sql_insert_statement (self, dict query, dict[str, Any] value_set) private
Build the sql INSERT query statement.
Statement Form: INSERT INTO table (column1, column2,...columnN)
    VALUES (value1, value2,...valueN)
Parameters:
    query (dict): {
        ['type'] -> (str) 'INSERT'
        ['table'] -> (str) name of table
        value_set -> (dict) set of key->value pairs to insert
            into table
    }
Returns:
    (str) INSERT sql statement.
Referenced by sql_query_from_array().
__sql_select_statement()
str lbk_library.datafile.DataFile.__sql_select_statement (self, dict query) private
Build the sql SELECT query statement.
Statement form: SELECT 'column1', 'column2',...  'columnN'
            FROM 'table_name'
            WHERE x = y
            ORDER BY 'columnX'
            LIMIT 5 OFFSET 0
Parameters:
    query (dict): {
        ['type'] -> (str) 'SELECT'
        ['table'] -> (str) name of table
        ['columns'] -> (list) column names for SELECT statement.
            Statement may use just '[*]' or '*' to select all
            columns. If omitted, defaults to '*'.
        ['where'] -> (str) providing the sql where_clause
            contents (without the 'WHERE"). Optional, if not
            present, selects all rows.
        ['order_by'] -> (str) providing the sql 'order by'
            clause (without the "ORDER_BY"). Optional
        ['limit'] -> (list)
            [0] = (int) limit value,
            [1] = (int) offset value. Optional
    }
Returns:
    (str) resultant sql query statement
Referenced by sql_query_from_array().
__sql_update_statement()
str lbk_library.datafile.DataFile.__sql_update_statement (self, dict query, dict value_set) private
Build the sql UPDATE query statement.
Statement Form:
    UPDATE table_name
    SET column1 = value1, column2 = value2...., columnN = valueN
    WHERE [condition];
Paraeters:
    query (dict): {
        ['type']  -> (str) 'UPDATE'
        ['table'] -> (str) name of table
        ['where'] -> (str) providing the sql where_clause
            contents selecting a specific row
    }
    value_set (dict): holding the set of values to update
Return;
    (str) resultant sql query statement
Referenced by sql_query_from_array().
_sql_error()
None lbk_library.datafile.DataFile._sql_error (self, str sql_text = "") protected
Display the error.
Parameters:
    sql_text (str): the sql command in error
Referenced by sql_query().
new_file()
None lbk_library.datafile.DataFile.new_file (cls, str filename, list[str] sql_statements)
Create and initialize the new DataFile.
Parameters:
    filename (str): full path to the datafile file to be created.
    sql_statements (list[str]): the sql definition of the
        datafile as a list of one or more SQL commands.
sql_close()
None lbk_library.datafile.DataFile.sql_close (self)
Close sql connection.
References __connection.
sql_connect()
bool lbk_library.datafile.DataFile.sql_connect (self, str datafile)
Connect to a specific datafile.
The variable __connection holds the connection object.
Parameters:
    datafile (str): path to datafile from program root
        directory.
Returns:
    (bool) True if connection succeeded, false otherwise
sql_fetchrow()
dict lbk_library.datafile.DataFile.sql_fetchrow (self, sqlite3.Cursor query_result)
Fetch current row from the query result set.
Parameters:
    query_result (Sqlite3.Cursor) The result of the previous
        query operation.
Returns:
    (dict) the current row as a dict(), None if no more rows or
        invalid query_result
sql_fetchrowset()
list lbk_library.datafile.DataFile.sql_fetchrowset (self, sqlite3.Cursor query_result)
Fetch all rows from a query result.
Parameters:
    query_result (Sqlite3.Cursor): The result of the previous
        query operation.
Returns:
    (list) The full set of rows as a list of dict objects,
        empty list if an invalid query result or when no rows
        are available.
sql_is_connected()
bool lbk_library.datafile.DataFile.sql_is_connected (self)
Check the status of the datafile connection.
Returns:
    (bool) True if connected, False if not
References __connection.
sql_nextid()
int lbk_library.datafile.DataFile.sql_nextid (self, sqlite3.Cursor query_result)
Get last inserted id after an insert statement.
This is only valid after Insert queries.
Parameters:
    query_result (sqlite3.Cursor): The result of a previous
        query operation.
Returns:
    (int) the last id assigned if the last query was valid,
        otherwise 0.
sql_query()
sqlite3.Cursor lbk_library.datafile.DataFile.sql_query (self, str query, dict values = {})
Execute a sql datafile query.
Parameters:
    query (str): Contains the SQL query statement which shall be
        executed.
    values (dict): The name: values pairs to inserted into the
        query; not all statements require this; default is
        empty dict.
Returns:
    (sqlite3.Cursor) the query result status if query succeeded,
         None Otherwise
Raises:
    sqlite3.OperationalError: if query is not valid
References __connection, and _sql_error().
sql_query_from_array()
str lbk_library.datafile.DataFile.sql_query_from_array (self, dict query, dict value_set = {})
Build parameterized sql statement from array.
Only DELETE, INSERT, UPDATE and SELECT statements are handled.
Parameters:
    query (dict): {
        ['type'] -> (str) one of 'DELETE', 'INSERT', 'SELECT',
                    or 'UPDATE'
        ['table'] -> (str) name of table to access
        ['where'] -> (str) providing the sql where_clause
            contents (without the 'WHERE").Required for DELETE
            statements, Optional for SELECT statements, not used
            by other statements.
        ['columns'] -> (list) column names for INSERT and SELECT
            statements. SELECT statement may use just [*] to
            select all columns. If ommitted, defaults to '*'.
        ['values'] -> (list) The set of values to insert or
            update. Order must match ['keys']
        ['order_by'] -> (str) providing the sql 'order by'
            clause (without the "ORDER_BY"). Optional for the
            SELECT statement, not used by other statments
        ['limit'] -> list: [0] =int(limit value)
                           [1] = int(offset value)
            Optional for SELECT statements, not used by
            other statements
        }
    value_set (dict): holds the key => value pairs for all the
        parameters needed in building the sql statement.
Returns:
    (str) The results of building the statement. An empty string
        will be returned if the query is not a dictionary or the
        type is not one of DELETE, INSERT, UPDATE or SELECT.
References __sql_delete_statement(), __sql_insert_statement(), __sql_select_statement(), and __sql_update_statement().
sql_validate_value()
Any lbk_library.datafile.DataFile.sql_validate_value (self, Any var)
Validate values for inclusion in SQL statements.
Returns:
    (Any) Updated values for None, Strings, and Booleans,
        otherwise the unchanged variable value.
Member Data Documentation
__connection
lbk_library.datafile.DataFile.__connection = None private
Referenced by sql_close(), sql_is_connected(), and sql_query().
__datafile_name
str lbk_library.datafile.DataFile.__datafile_name = "" private
datafile_name
lbk_library.datafile.DataFile.datafile_name = datafile
The documentation for this class was generated from the following file:
src/lbk_library/datafile.py