Project Library: lbk_library.gui.dialog.Dialog Class Reference
lbk_library.gui.dialog.Dialog Class Reference
Public Member Functions
None __init__ (self, QMainWindow parent, Dbal dbref, int operation)
Dbal get_dbref (self)
Element get_element (self)
None set_element (self, Element element)
Dbal get_operation (self)
None set_operation (self, int operation=VIEW_ELEMENT)
None set_combo_box_selections (self, QComboBox combo_box, list[str] selections, int|None selected=None)
bool action_cancel (self, Callable save_action, int action)
None message_information_close (self, str msg_text)
None message_question_changed_close (self, str changed_name)
None message_question_changed (self, str changed_name)
None message_question_no_changes (self)
def message_warning_selection (self, str name, str action)
None message_warning_failed (self, str operation)
None message_warning_invalid (self, str msg_text="")
QMessageBox.StandardButton message_box_exec (self, QMessageBox message_box)
Static Public Attributes
int VIEW_ELEMENT = 0
int ADD_ELEMENT = 1
int EDIT_ELEMENT = 2
int SAVE_NEW = 1
int SAVE_DONE = 2
Private Attributes
__dbref
__element
__operation
Detailed Description
Base class for the editing dialog forms.
Holds common functions used by all the editing dialog
forms.
Constructor & Destructor Documentation
__init__()
None lbk_library.gui.dialog.Dialog.__init__ (self, QMainWindow parent, Dbal dbref, int operation)
Initialize the form common elements.
Parameters:
    parent (QMainWindow): The parent window owning this dialog.
    dbref (Dbal): A reference to the current database
    operation (int): the editing operation, one of ADD_ELEMENT,
        EDIT_ELEMENT or VIEW_ELEMENT.
References lbk_library.gui.dialog.Dialog.__init__().
Member Function Documentation
action_cancel()
bool lbk_library.gui.dialog.Dialog.action_cancel (self, Callable save_action, int action)
Close the dialog.
Check if entries have changed. If so, ask if discard or save
entry and close dialog or stay on dialog.
Parameters:
    save_action (Callable): the method to save the form
        information
    action (int): type of save action, either Dialog.SAVE_NEW or
        Dialog.SAVE_DONE
Returns:
    (bool) True if dialog is closed, False if not.
References lbk_library.gui.dialog.Dialog.get_element(), lbk_library.gui.dialog.Dialog.message_box_exec(), lbk_library.gui.dialog.Dialog.message_question_changed_close(), and lbk_library.gui.dialog.Dialog.message_warning_invalid().
get_dbref()
Dbal lbk_library.gui.dialog.Dialog.get_dbref (self)
Get the reference to the current database.
Returns:
    (Dbal) reference to current database
References lbk_library.gui.dialog.Dialog.__dbref.
get_element()
Element lbk_library.gui.dialog.Dialog.get_element (self)
Get the element for this dialog.
Returns:
    (Element) the element for this form
References lbk_library.gui.dialog.Dialog.__element.
get_operation()
Dbal lbk_library.gui.dialog.Dialog.get_operation (self)
Get the current editing operation.
Returns:
    (int) One of ADD_ELEMENT, EDIT_ELEMENT or VIEW_ELEMENT.
References lbk_library.gui.dialog.Dialog.__operation.
message_box_exec()
QMessageBox.StandardButton lbk_library.gui.dialog.Dialog.message_box_exec (self, QMessageBox message_box)
Return the result of executing a prepare message box.
Parameters:
    message_box (QMessageBox): the box to execute.
Returns:
    (QMessageBox.StandardButton) the button clicked
message_information_close()
None lbk_library.gui.dialog.Dialog.message_information_close (self, str msg_text)
Display a "Success' message dialog for a form action.
Parameters:
    msg_text (str): text for message, may be empty string
Returns:
    (QMessageBox) The 'informational' message box ready for display.
message_question_changed()
None lbk_library.gui.dialog.Dialog.message_question_changed (self, str changed_name)
Display a message dialog warning of a form entry change.
Parameters:
    changed_name (str): the name of the changed form element
Returns:
    (QMessageBox) The 'changed' message box ready for display.
message_question_changed_close()
None lbk_library.gui.dialog.Dialog.message_question_changed_close (self, str changed_name)
Display a message dialog warning of a form entry change.
Parameters:
    changed_name (str): the name of the changed form element.
Return:
    (QMessageBox) The 'changed' message box ready for display.
message_question_no_changes()
None lbk_library.gui.dialog.Dialog.message_question_no_changes (self)
Display a message dialog noting no changes on the form.
Returns:
    (QMessageBox) The 'warning' message box ready for display.
message_warning_failed()
None lbk_library.gui.dialog.Dialog.message_warning_failed (self, str operation)
Display a message dialog warning of a failed operation.
Parameters:
    operation (str) the name of the failed operation.
Returns:
    (QMessageBox) The 'warning' message box ready for display.
message_warning_invalid()
None lbk_library.gui.dialog.Dialog.message_warning_invalid (self, str msg_text = "")
Display a message dialog warning of invalid entries on the form.
Parameters:
    msg_text (str): Text to add to message information, may
        be empty string
Returns:
    (QMessageBox) The 'warning' message box ready for display.
message_warning_selection()
def lbk_library.gui.dialog.Dialog.message_warning_selection (self, str name, str action)
Display message dialog warning 'name' selection is missing.
The selection has not been made so the 'action' cannot be
accomplished.
Parameters:
    name (str): the selected widget.
    action (str): action to take on selection.
Returns:
    (QMessageBox) The 'warning' message box ready for display.
set_combo_box_selections()
None lbk_library.gui.dialog.Dialog.set_combo_box_selections (self, QComboBox combo_box, list[str] selections, int | None selected = None)
Fill the combo box selection set.
Add the 'selections' to the combo box, optionally selecting the
'selected' item if given.
Paramters:
    combo_box (QComboBox): the combo box to initialize.
    selections (list[str]): available selections.
    selected (str): (Optional) the inital selection.
set_element()
None lbk_library.gui.dialog.Dialog.set_element (self, Element element)
Set the element for this dialog.
Parameters:
    element (Element): for this form
References lbk_library.gui.dialog.Dialog.__element.
set_operation()
None lbk_library.gui.dialog.Dialog.set_operation (self, int operation = VIEW_ELEMENT)
Set the operation for this dialog.
Parameters:
    operation (int): The current editing operation, one of
        Dialog.ADD_ELEMENT, Dialog.EDIT_ELEMENT or
        Dialog.VIEW_ELEMENT. Default operation is VIEW_ELEMENT
        (i.e. read only)
References lbk_library.gui.dialog.Dialog.__operation.
Member Data Documentation
__dbref
lbk_library.gui.dialog.Dialog.__dbref private
__element
lbk_library.gui.dialog.Dialog.__element private
__operation
lbk_library.gui.dialog.Dialog.__operation private
ADD_ELEMENT
int lbk_library.gui.dialog.Dialog.ADD_ELEMENT = 1 static
EDIT_ELEMENT
int lbk_library.gui.dialog.Dialog.EDIT_ELEMENT = 2 static
SAVE_DONE
int lbk_library.gui.dialog.Dialog.SAVE_DONE = 2 static
SAVE_NEW
int lbk_library.gui.dialog.Dialog.SAVE_NEW = 1 static
VIEW_ELEMENT
int lbk_library.gui.dialog.Dialog.VIEW_ELEMENT = 0 static
The documentation for this class was generated from the following file:
src/lbk_library/gui/dialog.py