Project Library: test_setup.Fish Class Reference
test_setup.Fish Class Reference
Public Member Functions
None __init__ (self, DataFile datafile, str table_name, int record_id=0)
None set_properties (self, dict[str, Any] properties)
str get_name (self)
dict[str, Any] set_name (self, str name)
str get_species (self)
dict[str, Any] set_species (self, str species)
str get_tank_number (self)
dict[str, Any] set_tank_number (self, int tank_number)
Public Member Functions inherited from lbk_library.element.Element
None __init__ (self, DataFile datafile, str table_name, dict[str, Any] default_values=None)
dict[str, Any] get_properties_from_datafile (self, str column_name, Any column_value)
int add (self)
bool delete (self)
bool update (self)
dict[str, Any] get_properties (self)
None set_validated_property (self, str property_name, bool is_valid, Any validated_value, Any default_value)
int get_record_id (self)
dict[str, Any] set_record_id (self, int record_id)
str get_remarks (self)
dict[str, Any] set_remarks (self, str remarks)
DataFile get_datafile (self)
str get_table (self)
dict[str, Any] get_initial_values (self)
None set_initial_values (self, dict[str, Any] initial_value_set)
None update_property_flags (self, str name, Any value, bool valid)
bool get_value_changed_flag (self, str entry_name)
bool set_value_changed_flag (self, str entry_name, Any entry_value)
bool have_values_changed (self)
None clear_value_changed_flags (self)
bool get_value_valid_flag (self, str entry_name)
bool set_value_valid_flag (self, str entry_name, bool entry_valid)
bool is_element_valid (self)
None clear_value_valid_flags (self)
Additional Inherited Members
Public Attributes inherited from lbk_library.element.Element
Validate validate = Validate()
Protected Member Functions inherited from lbk_library.element.Element
Any _get_property (self, str name)
None _set_property (self, str name, Any value)
Protected Attributes inherited from lbk_library.element.Element
dict _defaults = {"record_id": 0, "remarks": ""}
Constructor & Destructor Documentation
__init__()
None test_setup.Fish.__init__ (self, DataFile datafile, str table_name, int record_id = 0)
References __init__(), lbk_library.element.Element.clear_value_changed_flags(), lbk_library.element.Element.get_properties(), lbk_library.element.Element.get_properties_from_datafile(), lbk_library.element.Element.set_initial_values(), and lbk_library.element.Element.set_properties().
Referenced by __init__().
Member Function Documentation
get_name()
str test_setup.Fish.get_name (self)
References lbk_library.element.Element._get_property().
get_species()
str test_setup.Fish.get_species (self)
References lbk_library.element.Element._get_property().
get_tank_number()
str test_setup.Fish.get_tank_number (self)
References lbk_library.element.Element._get_property().
set_name()
dict[str, Any] test_setup.Fish.set_name (self, str name)
References lbk_library.element.Element._set_property(), and lbk_library.element.Element.validate.
Referenced by set_properties().
set_properties()
None test_setup.Fish.set_properties (self, dict[str, Any] properties)
Set the values of the Element properties array.
This must be overridden and called by the child class to handle
the full set of properties. This method sets the common
properties 'record_id' (contained in all Elements) and
'remarks' (contained in many Elements).
Each property is validated for type and value within an
acceptable range, with unacceptable values set to the
respective default values. Properties not part of the element
are discarded.
Parameters:
    properties (dict): object holding the element values. Keys
        must match the required keys of the element being
        modified, properties may be sparse.
Returns:
    (dict[str, list[str, bool, str]]) the results of setting the
        values as key:validation_results pairs. May be empty or
        sparse.
Reimplemented from lbk_library.element.Element.
References set_name(), set_properties(), set_species(), and set_tank_number().
Referenced by set_properties().
set_species()
dict[str, Any] test_setup.Fish.set_species (self, str species)
References lbk_library.element.Element._set_property(), and lbk_library.element.Element.validate.
Referenced by set_properties().
set_tank_number()
dict[str, Any] test_setup.Fish.set_tank_number (self, int tank_number)
References lbk_library.element.Element._set_property(), and lbk_library.element.Element.validate.
Referenced by set_properties().
The documentation for this class was generated from the following file:
tests/test_setup.py