Project Library: test_11_table_model Namespace Reference
test_11_table_model Namespace Reference
Functions
setup_table_model (tmp_path)
test_11_01_class_type (tmp_path)
test_11_02_cell_data_class (tmp_path)
test_11_03_load_cell_values (tmp_path)
test_11_04_rowCount (tmp_path)
test_11_05_columnCount (tmp_path)
test_11_06_flags (tmp_path)
test_11_07_header_data (tmp_path)
test_11_08_setHeaderData (tmp_path)
test_11_09_insert_rows (tmp_path)
test_11_10_delete_rows (tmp_path)
test_11_11_data (tmp_path)
test_11_12_setData (tmp_path)
Variables
src_path = os.path.join(os.path.realpath("."), "src")
list header_titles = ["Record Id", "Name", "Species", "Tank Number"]
list tool_tips = ["Tool Tip 0", "Tool Tip 1", "Tool Tip 2", "Tool Tip 3"]
list cell_alignments
normal_background = QBrush(QColor("white"))
error_background = QBrush(QColor("red"))
list column_names = ["record_id", "name", "species", "tank_number"]
list test_value_set
list datafile_definition
str datafile_name = "fish"
Detailed Description
Test the TableModel class.
File:       test_11_table_model.py
Author:     Lorn B Kerr
Copyright:  (c) 2024 Lorn B Kerr
License:    MIT, see file LICENSE
Function Documentation
setup_table_model()
test_11_table_model.setup_table_model (tmp_path)
Referenced by test_11_01_class_type(), test_11_02_cell_data_class(), test_11_03_load_cell_values(), test_11_04_rowCount(), test_11_05_columnCount(), test_11_06_flags(), test_11_07_header_data(), test_11_08_setHeaderData(), test_11_09_insert_rows(), test_11_10_delete_rows(), test_11_11_data(), and test_11_12_setData().
test_11_01_class_type()
test_11_table_model.test_11_01_class_type (tmp_path)
References setup_table_model().
test_11_02_cell_data_class()
test_11_table_model.test_11_02_cell_data_class (tmp_path)
References setup_table_model().
test_11_03_load_cell_values()
test_11_table_model.test_11_03_load_cell_values (tmp_path)
References setup_table_model().
test_11_04_rowCount()
test_11_table_model.test_11_04_rowCount (tmp_path)
References setup_table_model().
test_11_05_columnCount()
test_11_table_model.test_11_05_columnCount (tmp_path)
References setup_table_model().
test_11_06_flags()
test_11_table_model.test_11_06_flags (tmp_path)
References setup_table_model().
test_11_07_header_data()
test_11_table_model.test_11_07_header_data (tmp_path)
References setup_table_model().
test_11_08_setHeaderData()
test_11_table_model.test_11_08_setHeaderData (tmp_path)
References setup_table_model().
test_11_09_insert_rows()
test_11_table_model.test_11_09_insert_rows (tmp_path)
References setup_table_model().
test_11_10_delete_rows()
test_11_table_model.test_11_10_delete_rows (tmp_path)
References setup_table_model().
test_11_11_data()
test_11_table_model.test_11_11_data (tmp_path)
References setup_table_model().
test_11_12_setData()
test_11_table_model.test_11_12_setData (tmp_path)
References setup_table_model().
Variable Documentation
cell_alignments
list test_11_table_model.cell_alignments
Initial value:
=  [
    Qt.AlignmentFlag.AlignLeft,
    Qt.AlignmentFlag.AlignHCenter,
    Qt.AlignmentFlag.AlignRight,
    Qt.AlignmentFlag.AlignLeft,
]
column_names
list test_11_table_model.column_names = ["record_id", "name", "species", "tank_number"]
datafile_definition
list test_11_table_model.datafile_definition
Initial value:
=  [
    (
        'CREATE TABLE IF NOT EXISTS "fish"'
        '("record_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,'
        ' "name" TEXT DEFAULT NULL,'
        ' "species" TEXT DEFAULT NULL,'
        ' "tank_number" INTEGER)'
    ),
]
datafile_name
str test_11_table_model.datafile_name = "fish"
error_background
test_11_table_model.error_background = QBrush(QColor("red"))
header_titles
list test_11_table_model.header_titles = ["Record Id", "Name", "Species", "Tank Number"]
normal_background
test_11_table_model.normal_background = QBrush(QColor("white"))
src_path
test_11_table_model.src_path = os.path.join(os.path.realpath("."), "src")
test_value_set
list test_11_table_model.test_value_set
Initial value:
=  [
    [1, "Sammy", "shark", 1],
    [2, "Jamie", "cuttlefish", 7],
]
tool_tips
list test_11_table_model.tool_tips = ["Tool Tip 0", "Tool Tip 1", "Tool Tip 2", "Tool Tip 3"]