Project Library: test_09_dialog Namespace Reference
test_09_dialog Namespace Reference
Functions
base_setup (tmp_path, qtbot)
test_09_01_class_type (tmp_path, qtbot)
test_09_02_get_datafile (tmp_path, qtbot)
test_09_03_get_set_element (tmp_path, qtbot)
test_09_04_msg_info_close (tmp_path, qtbot)
test_09_05_msg_quest_changed_close (tmp_path, qtbot)
test_09_06_msg_quest_change (tmp_path, qtbot)
test_09_07_msg_quest_no_changes (tmp_path, qtbot)
test_09_08_msg_warning_selectio (tmp_path, qtbot)
test_09_09_msg_warning_failed (tmp_path, qtbot)
test_09_10_msg_warning_invalid (tmp_path, qtbot)
test_09_11_action_cancel (tmp_path, qtbot, mocker)
test_09_12_set_combo_box_selections (tmp_path, qtbot)
test_09_13_get_set_operation (tmp_path, qtbot)
test_09_13_update_error_flag (tmp_path, qtbot)
test_09_14_validate_dialog_entry (tmp_path, qtbot)
Variables
src_path = os.path.join(os.path.realpath("."), "src")
Detailed Description
Test the Dialog class.
File:       test_09_dialog.py
Author:     Lorn B Kerr
Copyright:  (c) 2023 Lorn B Kerr
License:    MIT, see file LICENSE
Function Documentation
base_setup()
test_09_dialog.base_setup (tmp_path, qtbot)
Referenced by test_09_01_class_type(), test_09_02_get_datafile(), test_09_03_get_set_element(), test_09_04_msg_info_close(), test_09_05_msg_quest_changed_close(), test_09_06_msg_quest_change(), test_09_07_msg_quest_no_changes(), test_09_08_msg_warning_selectio(), test_09_09_msg_warning_failed(), test_09_10_msg_warning_invalid(), test_09_11_action_cancel(), test_09_12_set_combo_box_selections(), test_09_13_get_set_operation(), test_09_13_update_error_flag(), and test_09_14_validate_dialog_entry().
test_09_01_class_type()
test_09_dialog.test_09_01_class_type (tmp_path, qtbot)
References base_setup().
test_09_02_get_datafile()
test_09_dialog.test_09_02_get_datafile (tmp_path, qtbot)
References base_setup().
test_09_03_get_set_element()
test_09_dialog.test_09_03_get_set_element (tmp_path, qtbot)
References base_setup().
test_09_04_msg_info_close()
test_09_dialog.test_09_04_msg_info_close (tmp_path, qtbot)
References base_setup().
test_09_05_msg_quest_changed_close()
test_09_dialog.test_09_05_msg_quest_changed_close (tmp_path, qtbot)
References base_setup().
test_09_06_msg_quest_change()
test_09_dialog.test_09_06_msg_quest_change (tmp_path, qtbot)
References base_setup().
test_09_07_msg_quest_no_changes()
test_09_dialog.test_09_07_msg_quest_no_changes (tmp_path, qtbot)
References base_setup().
test_09_08_msg_warning_selectio()
test_09_dialog.test_09_08_msg_warning_selectio (tmp_path, qtbot)
References base_setup().
test_09_09_msg_warning_failed()
test_09_dialog.test_09_09_msg_warning_failed (tmp_path, qtbot)
References base_setup().
test_09_10_msg_warning_invalid()
test_09_dialog.test_09_10_msg_warning_invalid (tmp_path, qtbot)
References base_setup().
test_09_11_action_cancel()
test_09_dialog.test_09_11_action_cancel (tmp_path, qtbot, mocker)
References base_setup().
test_09_12_set_combo_box_selections()
test_09_dialog.test_09_12_set_combo_box_selections (tmp_path, qtbot)
References base_setup().
test_09_13_get_set_operation()
test_09_dialog.test_09_13_get_set_operation (tmp_path, qtbot)
References base_setup().
test_09_13_update_error_flag()
test_09_dialog.test_09_13_update_error_flag (tmp_path, qtbot)
References base_setup().
test_09_14_validate_dialog_entry()
test_09_dialog.test_09_14_validate_dialog_entry (tmp_path, qtbot)
References base_setup().
Variable Documentation
src_path
test_09_dialog.src_path = os.path.join(os.path.realpath("."), "src")